# Generated by Django 5.1.2 on 2024-10-14 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_remove_employee_role_employeerole_employee_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department",
                to="project.department",
            ),
        ),
    ]
