# Generated by Django 5.1.3 on 2024-11-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_team_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeerole',
            name='department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
