# Generated by Django 5.1.2 on 2024-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0010_remove_employee_role_remove_permission_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                    ("InProgress", "InProgress"),
                    ("OnTrack", "OnTrack"),
                    ("Delayed", "Delayed"),
                    ("Testing", "Testing"),
                    ("OnHold", "OnHold"),
                    ("Approved", "Approved"),
                    ("Canceled", "Canceled"),
                    ("Planning", "Planning"),
                    ("Completed", "Completed"),
                    ("Closed", "Closed"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
