# Generated by Django 5.1.2 on 2024-11-23 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.TextField(max_length=50)),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "day",
                    models.TextField(
                        choices=[
                            ("SATURDAY", "SATURDAY"),
                            ("SUNDAY", "SUNDAY"),
                            ("MONDAY", "MONDAY"),
                            ("TUESDAY", "TUESDAY"),
                            ("WEDNESDAY", "WEDNESDAY"),
                            ("THURSDAY", "THURSDAY"),
                            ("FRIDAY", "FRIDAY"),
                        ]
                    ),
                ),
                ("color", models.TextField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine.routinecategory",
                    ),
                ),
            ],
        ),
    ]
